### ISSUE TITLE
could not connect to xstream repo

### ISSUE THREAD

**Issue by damnms** [streamxstream/xStream-FAQ#10]
Habe wie angegeben das Repo installiert, das ging auch, aber wenn ich jetzt was davon installieren mag, meckert er, dass das Repo nicht da ist. Ist das down?

**Comment by DWH-WFC** [comment]
Kann sein das das bei der Umstellung war.
Bitte Repo neu installieren.
https://streamxstream.github.io/xStreamRepoWeb/

**Comment by binnichtaktiv** [comment]
> Kann sein das das bei der Umstellung war. Bitte Repo neu installieren. https://streamxstream.github.io/xStreamRepoWeb/

danke hat funktioniert🫶🏻💙
