### ISSUE TITLE
Kodi Crashed After "xStream Error please view the protocol" 

### ISSUE THREAD

**Issue by wsa-gapps** [streamxstream/xStream-FAQ#20]
Hello, im Used a TV box with Kodi and your xStream Plugin.

It works for one or two days very good, an then kodi says, xStream Error, please view the protocol.
And then Kodi only crashes , and kodi says ever the Xstream Error message.

When i Reinstall Kodi and the Plugin, then all works again fine for one or two days.

how i can solve it?

**Comment by DWH-WFC** [comment]
Bitte nutzen Sie das richtige GIT und füllen Sie vollständig das Fehler Protokoll aus.

https://github.com/streamxstream/plugin.video.xstream/issues/new?assignees=&labels=Fehlermeldung&projects=&template=fehler-melden.md&title=Fehler+Melden
