### ISSUE TITLE
Aniworld not working

### ISSUE THREAD

**Issue by Lordhinz1221** [streamxstream/xStream-FAQ#21]
When I try to search something it always tells me that "the entry was not found" can someone pls help

![Screenshot_20240211_233416_Kodi](https://github.com/streamxstream/xStream-FAQ/assets/159732685/330c5019-8d51-4e73-b40d-6639f0991189)

**Comment by DWH-WFC** [comment]
Bitte Issue im Plugin erstellen.

https://streamxstream.github.io/xStreamRepoWeb/

Hier zu finden.

MfG
