### ISSUE TITLE
[Feature] search history

### ISSUE THREAD

**Issue by damnms** [streamxstream/xStream-FAQ#24]
It would be very nice if there would be some sort of history when searching for a movie. E.g. i search for "an ultra long title that took me endless time on my cheap crappy remote to press the virtual keyboard" and find some streams, watch one and then have some playback issue or network issue or the stream maybe aborts, then i have to enter this very long search text again :/

What i also noticed: when watching a stream that was found using the search, when this stream abruptly ends (e.g. network issues), i do not land at the xstream "page" in kodi but in "Files" - thats a bit odd.

**Comment by DWH-WFC** [comment]
Nein möchten wir nicht integrieren.
Hier bitte keine Issues eröffnen bitte direkt im Plugin Git.
